version: "3.3"
services:
  duckdb_fdw0:
     build: .
     ports:
         - "5449:5432"
     volumes:
         - mdata:/pgduck
     environment:
         - POSTGRES_USER=postgres
         - POSTGRES_DB=postgres
         - POSTGRES_PASSWORD=qwert         
         
volumes:
  mdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/pete/tmp/pgduck
